server {
    listen 0.0.0.0:80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "frame-ancestors http://localhost:28471" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
